name: Publish MicroEndpoints to NuGet

on:
  push:
    branches:
      - main # Your default release branch
    paths:
      - 'src/MicroEndpoints/**'

jobs:
  publish:
    name: Build and Publish
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      # Required for a specific dotnet version that doesn't come with ubuntu-latest / windows-latest
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x' # Change the dotnet version to the latest LTS version (6.0.x)

      # Publish
      - name: Create the package
        run: dotnet pack -c Release -o . src/MicroEndpoints/MicroEndpoints.csproj
        
      - name: Publish to nuget.org
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }} # Use environment variable
        run: nuget push MicroEndpoints.*.nupkg -src https://api.nuget.org/v3/index.json ${{secrets.NUGET_API_KEY}}
